// Actions
export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";

export const REQUEST_INITIAL_USERS_PENDING = "REQUEST_INITIAL_USERS_PENDING";
export const REQUEST_INITIAL_USERS_SUCCESS = "REQUEST_INITIAL_USERS_SUCCESS";
export const REQUEST_INITIAL_USERS_FAILED = "REQUEST_INITIAL_USERS_FAILED";
